import json
import requests

APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwMkGi_5S0OBH5esmLyRAbx9BBEv-OMLWRcTS1IHTi682AF5xMNtZOLxVv_Whamh3RZMw/exec"

data = {
    "appName": "CISSP",
    "flashcards": [
        # Topic 1: Security and Risk Management
        {"Topic": "1", "Subtopic": "N/A", "Front": "ISC2 Code of Professional Ethics", "Back": "Mandatory ethical system for members. Requires protecting society, acting honorably, providing competent service to principals, and maintaining the industry's collective professional reputation and integrity."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Confidentiality", "Back": "Security principle ensuring information is hidden from unauthorized eyes. Prevents unwanted disclosure through encryption, access controls, and strict physical security measures within organizations."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Integrity", "Back": "Assurance that data is accurate and untainted by unauthorized modifications. Maintained through hashing and digital signatures to provide reliable and trustworthy organizational information."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Availability", "Back": "Goal guaranteeing that systems and data are reachable when authorized users require them. Achieved through redundancy, backups, and effective organizational disaster recovery planning."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Authenticity", "Back": "The property of being genuine and verifiable. Ensures that a message or user is truly who they claim to be through strong identification methods."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Nonrepudiation", "Back": "Principle preventing denial of actions in a communication. uses digital signatures and audit logs to provide irrefutable legal evidence of involvement and activity."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Security Governance Principles", "Back": "Rules aligning security strategies with business goals. Establishes oversight, roles, and responsibilities to manage risk and ensure organizational compliance with various data laws."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Alignment of Security Function", "Back": "Integrating security into the core organizational plan. Ensures that all protective measures support business goals, mission, and long-term strategic objectives and success."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Acquisitions", "Back": "Security challenges introduced when buying another company. requires due diligence to identify potential vulnerabilities and ensure that new assets meet organizational protection standards."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Divestitures", "Back": "Process of securing data when part of an organization is sold. requires careful management to prevent unauthorized transfer of sensitive information to the buyer."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Governance Committees", "Back": "Group of senior managers overseeing the security program. ensures that protective measures are aligned with business needs and receive adequate resources and support."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Organizational Roles", "Back": "Defining who is responsible for specific security tasks. ensures accountability and clarity, preventing gaps in the organizational defense strategy and overall risk management."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Security Control Frameworks", "Back": "Structured sets of guidelines like ISO or NIST. provides a common language and playbook for managing risk and ensuring consistent organizational defensive strategies."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Due Care", "Back": "The legal and ethical obligation to implement reasonable security measures. it represents the specific act of doing the right thing to prevent harm."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Due Diligence", "Back": "Ongoing process of verifying that security measures are effective. involves audits and monitoring to ensure constant protection and full regulatory and organizational compliance."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Cybercrimes", "Back": "Illegal activities conducted via computers or networks. helps organizations understand their rights and responsibilities when responding to data breaches and external malicious attacks."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Data Breaches", "Back": "Unauthorized access to sensitive information. Requires immediate response, containment, and notification to authorities and individuals to minimize impact and maintain legal compliance and trust."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Intellectual Property Requirements", "Back": "Measures used to safeguard original creations like patents. Essential for maintaining competitive advantage and preventing unauthorized disclosure of sensitive organizational trade secrets and designs."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Import and Export Controls", "Back": "Regulations restricting the transfer of sensitive technologies across borders. organizations must follow these rules to ensure national security and regulatory compliance for encryption."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Transborder Data Flow", "Back": "Movement of digital information across national boundaries. requires management to comply with international privacy laws and protect organizational data during global transmissions and sharing."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "GDPR", "Back": "Comprehensive data protection regulation from the EU. mandates high privacy standards and gives individuals control over how their personal information is collected and processed."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Privacy Impact Assessment", "Back": "Evaluation of how personal data is handled within a project. it identifies privacy risks and ensures compliance with regulations before processing sensitive information begins."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Security Policy", "Back": "High-level document stating management's security intent. outlines rules for protecting assets, providing the foundation for all organizational standards and operating procedures and guidelines."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Security Standards", "Back": "Mandatory requirement establishing consistent baselines for hardware or software. ensures security is applied uniformly across the entire organizational infrastructure and environment and assets."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Security Procedures", "Back": "Detailed, step-by-step guide for performing specific tasks. ensures that policies are followed consistently by all employees during daily operations and response and recovery."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Security Guidelines", "Back": "Recommended best practices offering flexibility in policy implementation. unlike standards, these are not mandatory but provide helpful advice for unique organizational security scenarios."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Business Impact Analysis", "Back": "Systematic investigation into critical functions. it identifies recovery priorities and targets to ensure resilience during major disruptive events and cyber attacks and incidents."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Candidate Screening", "Back": "Personnel security process involving background checks and vetting. ensures new hires are trustworthy and reduces the risk of insider threats to sensitive assets."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Onboarding", "Back": "Integrating new employees with access and training. ensures personnel understand responsibilities and follow established organizational security policies and procedures from their first day of work."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Termination Processes", "Back": "Formal process of removing access when employees leave. critical for preventing orphaned accounts and reducing risk from former employees causing organizational system harm."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Risk Appetite", "Back": "The level of risk an organization is willing to accept to achieve goals. defines decision-making boundaries and determines which threats require active mitigation."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Risk Tolerance", "Back": "The specific level of variation an organization can accept regarding objectives. provides granular thresholds for acceptable risk levels within individual projects and departments."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Threat Modeling", "Back": "Systematic process to identify vulnerabilities during design. uses visual representations to anticipate attack vectors and develop effective organizational risk mitigation strategies and protective controls."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "SCRM", "Back": "Supply Chain Risk Management. Identifying and mitigating risks across the acquisition lifecycle. ensures security is a core requirement when vetting third-party software and hardware."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Silicon Root of Trust", "Back": "Hardware-level security component verifying system firmware. provides a secure foundation to prevent low-level tampering and malicious implants within critical organizational computer systems and infrastructure."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Software Bill of Materials", "Back": "List of all ingredients in a program. provides transparency to help organizations manage supply chain risks by identifying vulnerable third-party components within software."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Security Champions", "Back": "Staff members who promote security within their teams. they act as liaisons between security departments and other business units to foster a culture of protection."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Gamification", "Back": "Using game design elements in security training. increases employee engagement and retention of security concepts by making the learning process more interactive and rewarding."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Cryptocurrency", "Back": "Digital currency using encryption for security. poses unique risks to organizations, including theft and its use in ransomware payments, requiring specialized security and monitoring controls."},
        {"Topic": "1", "Subtopic": "N/A", "Front": "Blockchain", "Back": "Distributed ledger technology providing transparency and integrity. offers potential security benefits for tracking transactions and verifying data, but requires careful implementation to avoid new organizational vulnerabilities."},

        # Topic 2: Asset Security
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Owner", "Back": "Senior manager responsible for specific asset protection. Defines classification, determines access rights, and ensures compliance with legal handling requirements throughout the entire lifecycle."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Custodian", "Back": "Individual performing hands-on technical protection tasks. Responsible for maintaining backups, ensuring data integrity, and implementing security controls as directed by the primary organizational owner."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Processor", "Back": "Third-party entity handling personal information for a controller. Must follow strict contractual instructions and implement specific security measures required by international data protection laws."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Controller", "Back": "Entity determining why and how personal data is processed. Legally responsible for protecting individual privacy and ensuring transparency in all organizational collection activities."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data at Rest", "Back": "Information stored on physical or virtual media. Protected primarily through encryption and physical access controls to prevent unauthorized retrieval or organizational hardware theft."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data in Transit", "Back": "Information moving across networks between systems. Secured using protocols like TLS and IPsec to prevent interception or modification during the organizational data transmission process."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data in Use", "Back": "Active information currently being processed in CPU or RAM. Requires memory protection and secure enclaves to prevent unauthorized access while the data is manipulated."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Classification", "Back": "Categorizing information based on sensitivity and impact if compromised. Guides the selection of appropriate security controls and handling requirements for all organizational assets."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Asset Inventory", "Back": "Comprehensive listing of all hardware and software components. Provides visibility into protection needs and forms the basis for effective organizational risk management strategies."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Lifecycle", "Back": "Stages information passes through from creation to destruction. includes storage, usage, and sharing, requiring specific controls to ensure constant organizational data protection throughout."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Retention", "Back": "Storing information for a specified period for legal reasons. must be balanced with privacy requirements to ensure that unnecessary risk is not accumulated."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Remanence", "Back": "Residual information remains after standard deletion attempts. Poses significant security risk unless neutralized through purging, degaussing, or complete physical destruction of organizational media."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Degaussing", "Back": "Using powerful magnetic fields to erase data. Renders information unrecoverable and is essential for securely disposing of organizational hard drives and magnetic storage media."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Purging", "Back": "Decommissioning process making data unrecoverable even against laboratory attacks. More thorough than clearing, involving overwriting or hardware-level sanitization for sensitive organizational storage media."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Scoping", "Back": "Determining which security controls from a baseline apply. Streamlines compliance by removing requirements that do not fit the specific organizational asset or system environment."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Tailoring", "Back": "Adjusting generalized security controls to fit unique needs. Ensures chosen protections are effective and operationally efficient for specific sensitive organizational information and hardware assets."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Digital Rights Management", "Back": "Technological protections used to control access to content. prevents unauthorized copying, sharing, or modification of digital assets through encryption and strict licensing keys."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Loss Prevention", "Back": "Technical solution monitoring and blocking sensitive data transfers. Identifies restricted information using patterns and labels to prevent accidental leakage from the organizational network."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Cloud Access Security Broker", "Back": "Gatekeeper between users and cloud providers. Enforces security policies, provides visibility, and protects organizational data during external transfers to various cloud services."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Anonymization", "Back": "Irreversibly stripping personal identifiers from a dataset. protects privacy by ensuring individuals cannot be identified, allowing data to be safely used for organizational analysis."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Pseudonymization", "Back": "Replacing identifiers with pseudonyms to protect privacy. Unlike anonymization, this process is reversible if the mapping key is available, requiring careful organizational management."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Masking", "Back": "Hiding sensitive data by replacing it with fake values. Often used in testing to protect real organizational information while allowing application functionality checks."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Tokenization", "Back": "Replacing sensitive elements with non-sensitive tokens. The original information is stored in a secure vault, reducing the risk of exposure during organizational processing."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Sovereignty", "Back": "Principle that data is subject to local jurisdiction laws. critical consideration when selecting organizational cloud storage locations to ensure compliance with legal requirements."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Asset Tagging", "Back": "Attaching unique identifiers to physical equipment. improves inventory management and ensures that all organizational hardware can be tracked and secured throughout its lifecycle."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "End of Life", "Back": "The date when a manufacturer stops selling a product. Signifies that hardware or software will soon lose support and required security updates."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "End of Support", "Back": "Stage where a vendor stops providing security patches. Assets in this phase are highly vulnerable and must be replaced immediately to protect."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Data Steward", "Back": "Operational role responsible for ensuring data quality. They assist owners by maintaining data standards and facilitating day-to-day accuracy within the organizational information environment."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Privacy Impact Assessment", "Back": "Evaluation of how personal data is handled within a project. it identifies privacy risks and ensures compliance with regulations before processing sensitive information."},
        {"Topic": "2", "Subtopic": "N/A", "Front": "Information Labeling", "Back": "Physical or digital markings indicating an asset's classification level. Labels guide users on proper handling and ensure security controls are applied consistently."},

        # Topic 3: Security Architecture and Engineering
        {"Topic": "3", "Subtopic": "N/A", "Front": "Bell-LaPadula Model", "Back": "Confidentiality-focused state machine model. Enforces 'no read up' and 'no write down' rules to prevent unauthorized access to sensitive information at higher security levels."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Biba Model", "Back": "Integrity-focused security model. Enforces 'no read down' and 'no write up' rules to prevent data corruption from lower-integrity sources or unauthorized modifications."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Clark-Wilson Model", "Back": "Commercial integrity model using well-formed transactions. Requires that all changes to data are performed through authorized programs and enforces strict organizational separation of duties."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Brewer-Nash Model", "Back": "Chinese Wall model preventing conflicts of interest. dynamically restricts access based on a user's previous organizational data access history to maintain integrity."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Trusted Computing Base", "Back": "Hardware, software, and firmware critical to security policy enforcement. must be tamper-proof and thoroughly tested to ensure it provides a reliable organizational defense foundation."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Reference Monitor", "Back": "Abstract component mediating every access request to objects. verifies authorization against organizational security policy and must be always invoked, tamper-proof, and small."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Common Criteria", "Back": "International standard for evaluating IT security. uses EAL grades to provide a consistent measure of an organizational product's security capabilities and effectiveness."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Trusted Platform Module", "Back": "Hardware chip providing secure cryptographic key storage. Enables organizational hardware integrity checks and protects against firmware-level tampering and unauthorized system-level modifications and changes."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Hardware Security Module", "Back": "Physical device protecting digital keys for strong authentication. provides highly secure cryptographic processing and prevents key extraction through physical and logical organizational barriers."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Symmetric Encryption", "Back": "Method using a single shared key for locking and unlocking. it is fast and efficient for processing large organizational information volumes and assets."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Asymmetric Encryption", "Back": "Public-key cryptography using linked key pairs. enables secure key exchange and digital signatures, ensuring confidentiality and integrity between various organizational and external parties."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Defense in Depth", "Back": "Layered approach using multiple controls to protect assets. ensures that if one barrier fails, others are in place to prevent organizational breaches."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Least Privilege", "Back": "Granting only minimum access needed for functions. limits potential damage from compromised accounts and is a fundamental design requirement for all organizational systems."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Zero Trust Architecture", "Back": "Security model assuming no entity is trusted by default. requires continuous verification of every organizational user and device, regardless of their network location."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Industrial Control Systems", "Back": "Systems managing critical infrastructure like power. require specialized measures to protect against physical impacts and ensure constant organizational availability of essential services."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Microservices Architecture", "Back": "Software design using small, independent services. simplifies security by isolating components, ensuring a breach in one service doesn't compromise the entire organizational application."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Containerization Security", "Back": "Isolating applications within lightweight containers. requires image scanning and monitoring to prevent malware from spreading between different organizational workloads and information system environments."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Edge Computing Security", "Back": "Distributed architecture bringing processing near data sources. requires localized controls to protect organizational info before transmission to central corporate or cloud servers."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Secure Defaults", "Back": "Pre-configured settings providing maximum protection. requires users to explicitly enable risky features, reducing the likelihood of accidental organizational security vulnerabilities and gaps."},
        {"Topic": "3", "Subtopic": "N/A", "Front": "Fail-Safe Design", "Back": "Principle where systems default to secure states upon failure. prevents unauthorized access or organizational harm when technical components stop functioning correctly."},

        # Topic 4: Communication and Network Security
        {"Topic": "4", "Subtopic": "N/A", "Front": "OSI Model", "Back": "Seven-layer conceptual framework for network communications. Standardizes how different organizational hardware and software interact, from physical connections to high-level application services."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "TCP/IP Protocol Suite", "Back": "Four-layer model powering the internet. includes Link, Internet, Transport, and Application layers, providing a practical framework for efficient organizational data transmission."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "IPsec Security", "Back": "Protocol suite authenticating and encrypting IP packets. provides strong confidentiality and integrity for organizational network traffic, essential for secure VPNs and communication."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "TLS Security", "Back": "Protocol providing secure communication over networks. encrypts data between organizational applications and servers, ensuring privacy for web browsing, email, and digital transmissions."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "Network Segmentation", "Back": "Dividing a network into isolated zones. it is a critical operational control that limits lateral movement of attackers and contains breaches."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "SDN", "Back": "Software-Defined Networking. Decouples network control from the forwarding plane. Enables centralized management, allowing security policies to be applied dynamically and consistently."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "VLAN", "Back": "Logical network segments within a switch. it improves organizational security and performance by isolating traffic between different departments on shared hardware."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "VPN", "Back": "Secure, encrypted tunnel over untrusted networks. Enables organizational users to access internal resources privately, protecting sensitive information from interception and maintaining confidentiality."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "DMZ", "Back": "Separate network segment hosting public-facing services. It isolates these systems from sensitive internal networks, reducing risk if an external server is compromised."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "CDN", "Back": "Content Delivery Network. Distributed network of servers delivering web content based on user location. improves performance and provide protection against DDoS."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "NAC", "Back": "Network Access Control. System restricting network entry to authorized devices. it ensures that all organizational systems meet protection standards before connecting."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "WPA3", "Back": "Latest Wi-Fi security protocol. Provides stronger encryption and improved protection against brute-force attacks compared to WPA2, ensuring secure organizational wireless connectivity."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "DNSSEC", "Back": "Security extension for the Domain Name System. uses digital signatures to verify data integrity and prevent cache poisoning attacks against organizational users."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "Microsegmentation", "Back": "Granular network security creating secure zones around individual workloads. prevents lateral movement of threats within organizational data centers and complex cloud environments."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "WAF", "Back": "Web Application Firewall. Security device protecting applications by filtering HTTP traffic. it prevents attacks like SQL injection and cross-site scripting."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "API Gateway", "Back": "Management tool acting as a single entry point for API traffic. enforces security policies, provides rate limiting, and protects underlying services."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "BGP Security", "Back": "Protections for the routing protocol connecting autonomous systems. essential for maintaining the overall security and integrity of global organizational internet routing."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "Zero Trust Network", "Back": "Security model where no device is trusted by default. requires strict identity verification and least privilege for every connection within organizational infrastructure."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "EDR", "Back": "Endpoint Detection and Response. Security solution monitoring endpoints for threats. provides advanced detection and automated response to identify and neutralize sophisticated attacks."},
        {"Topic": "4", "Subtopic": "N/A", "Front": "UTM", "Back": "Unified Threat Management. Single appliance consolidating multiple security functions like firewall and antivirus. simplifies management and provides comprehensive protection for networks."}
    ]
}

def upload_data(data):
    try:
        response = requests.post(APPS_SCRIPT_URL, json=data, timeout=60)
        print(f"Status: {response.status_code}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    upload_data(data)
