import json
import requests

APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwMkGi_5S0OBH5esmLyRAbx9BBEv-OMLWRcTS1IHTi682AF5xMNtZOLxVv_Whamh3RZMw/exec"

data = {
    "appName": "CISSP",
    "flashcards": [
        # Topic 5: Identity and Access Management (IAM)
        {"Topic": "5", "Subtopic": "N/A", "Front": "Identification", "Back": "Process of a user claiming an identity. involves providing a unique username or ID within the organizational environment to start access."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Authentication", "Back": "Process of verifying a claimed identity. requires providing credentials like passwords or tokens to prove the user is who they claim to be."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Authorization", "Back": "Process of granting or denying access to resources. determined by organizational policy and permissions, ensuring users only reach authorized information and systems."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Accountability", "Back": "Ability to link actions to an individual. achieved through unique IDs and audit logging, ensuring organizational users are responsible for their system interactions."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "RBAC", "Back": "Role-Based Access Control. Grants permissions based on job function. simplifies organizational management and ensures employees only have the access they need for duties."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "DAC", "Back": "Discretionary Access Control. Allows resource owners to determine access. provides flexibility but is difficult to manage securely in large organizational information system environments."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "MAC", "Back": "Mandatory Access Control. Restricts access based on security labels. enforced by the system, it is the most secure organizational model for sensitive information."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "ABAC", "Back": "Attribute-Based Access Control. Grants access based on user/resource characteristics. provides highly granular organizational control suitable for complex and evolving security and system requirements."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Least Privilege", "Back": "Granting only minimum access needed for tasks. reduces organizational attack surface and limits potential damage from compromised accounts or accidental human errors and mistakes."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Need-to-Know", "Back": "Restricting information access to individuals needing it for tasks. fundamental organizational security principle that prevents unnecessary exposure of sensitive data and information assets."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Identity Federation", "Back": "Linking user identities across different security domains. allows users to access organizational resources in partner systems using primary internal corporate credentials and identification."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Provisioning", "Back": "Process of creating user accounts and access. must be handled securely to ensure new organizational employees receive only the permissions required for roles."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Deprovisioning", "Back": "Formal process of removing access when no longer required. critical for preventing orphaned accounts and reducing unauthorized access risks in the organizational environment."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Access Review", "Back": "Periodic evaluation of user permissions. ensures access still aligns with roles and identifies unnecessary entitlements for immediate removal from the organizational identity system."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "IDaaS", "Back": "Identity as a Service. Cloud-based management solution. simplifies deployment and provides scalable identity management for organizations with diverse and evolving IT environments and needs."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Privileged Access Management", "Back": "Specialized tools securing administrative accounts. provides extra protection including session recording to reduce the time high-level credentials are exposed within organizational systems."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Single Sign-On", "Back": "Mechanism allowing one authentication for multiple systems. it reduces password fatigue and improves organizational user experience while simplifying administrative identity management and oversight."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Kerberos", "Back": "Ticket-based protocol providing SSO. uses a trusted third party to verify organizational identities and provide session keys, ensuring secure communication across networks."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "OAuth", "Back": "Open standard for access delegation. allows organizational users to grant third-party apps limited access to resources without revealing secret passwords or other credentials."},
        {"Topic": "5", "Subtopic": "N/A", "Front": "Biometric Authentication", "Back": "Credential based on physical characteristics. includes fingerprints, providing high security for sensitive organizational systems while requiring careful privacy management and error rate oversight."},

        # Topic 6: Security Assessment and Testing
        {"Topic": "6", "Subtopic": "N/A", "Front": "Vulnerability Assessment", "Back": "Process of identifying and prioritizing known security weaknesses. provides regular check-ups and helps organizational administrators prioritize remediation and patching efforts effectively based on risk."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Penetration Testing", "Back": "Authorized simulated attack evaluating security defenses. identifies organizational gaps and tests control effectiveness against real-world adversaries and sophisticated cyber threats and attack methods."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Security Audit", "Back": "Formal evaluation of adherence to established standards. provide objective evidence of compliance and identifies areas for improvement to maintain a robust posture."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Static Analysis", "Back": "Examining code for vulnerabilities without execution. provides immediate feedback to developers, identifying common organizational coding errors like injection flaws early in the lifecycle."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Dynamic Analysis", "Back": "Testing running applications for security flaws. identifies issues visible only during execution, such as organizational session management errors and application-layer security vulnerabilities."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Fuzz Testing", "Back": "Providing random or invalid data as input. identifies organizational vulnerabilities like crashes and memory leaks that could be exploited by adversaries to compromise systems."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Misuse Case Testing", "Back": "Evaluating system response to malicious activities. identifies organizational security gaps and helps design applications that are resilient against common adversary methods and vectors."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Synthetic Transactions", "Back": "Testing a system by simulating user behavior. monitors application availability and performance while identifying potential security issues before they affect real organizational users."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Log Analysis", "Back": "Systematic review of security logs for threats. automated tools help organizational teams sift through data to spot anomalies and indicators of compromise."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Security Metric", "Back": "Quantitative measure of protection performance. used to track control effectiveness and provide a data-driven basis for making informed organizational security and management decisions."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Continuous Monitoring", "Back": "Ongoing evaluation of the organizational security posture. provides real-time visibility into control effectiveness and helps detect threats and compliance issues as they arise."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Risk Matrix", "Back": "Tool prioritizing vulnerabilities by severity and impact. helps organizational management decide which threats require immediate attention and where to allocate limited security resources."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Security Baseline", "Back": "Minimum required security controls for assets. provides a foundation for protection and ensures a consistent security posture across the entire organizational information environment."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Threat Attribution", "Back": "Process identifying the specific adversary responsible. helps organizations understand motives and methods, informing the development of targeted and effective organizational defense and protection."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Indicators of Compromise", "Back": "Evidence that a breach has occurred. identifying IoCs is a key goal of organizational log analysis and continuous monitoring to detect threats."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Red Team Exercise", "Back": "Adversarial simulation attempting to breach organizational defenses. provides a realistic test of the overall security posture and the effectiveness of detective and preventive controls."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Blue Team", "Back": "Personnel responsible for defending organizational systems. they use various tools and procedures to monitor, detect, and respond to cyber threats in real-time."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Vulnerability Life Cycle", "Back": "Stages of identifying and fixing security gaps. includes discovery, analysis, prioritization, fixing, and retesting to ensure organizational assets remain constantly protected from threats."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "Security Assessment Framework", "Back": "Structured set of guidelines for security evaluations. provides consistent and repeatable processes for identifying organizational vulnerabilities and ensuring all mandated data protection standards."},
        {"Topic": "6", "Subtopic": "N/A", "Front": "System Hardening", "Back": "Securing systems by removing unnecessary services and vulnerabilities. a critical corrective action identified during organizational assessments to reduce the overall attack surface effectively."},

        # Topic 7: Security Operations
        {"Topic": "7", "Subtopic": "N/A", "Front": "Incident Response", "Back": "Coordinated effort managing a security breach. Aimed at containing the threat and restoring operations while minimizing damage and overall organizational financial loss."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Digital Forensics", "Back": "Gathering and analyzing electronic evidence after an incident. aims to understand breaches and identify perpetrators while maintaining a strict chain of custody."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Patch Management", "Back": "Strategic process of applying software updates. critical corrective control that closes known vulnerabilities and strengthens the overall security posture of organizational technology assets."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Vulnerability Management", "Back": "Cycle identifying and fixing security gaps. ensures organizational systems remain protected against new threats through regular scanning and effective prioritization of remediation and tasks."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Change Management", "Back": "Formal process managing system modifications. requires organizational approval to prevent unauthorized changes and reduce the risk of accidental security vulnerabilities or operational disruptions."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Asset Management", "Back": "Tracking hardware and software components. provides visibility into the attack surface and ensures all assets receive required security updates and maintenance organizational-wide."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Personnel Security", "Back": "Measures ensuring employees are trustworthy and trained. includes background checks and awareness programs to reduce the risk of organizational insider threats and errors."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Physical Security", "Back": "Protecting tangible assets from physical threats. include locks, cameras, and barriers designed to prevent unauthorized individuals from reaching sensitive areas or critical hardware."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "BCP", "Back": "Business Continuity Planning. Strategy ensuring critical functions survive disasters. focuses on organizational resilience and the ability to maintain operations during major disruptive events."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "DRP", "Back": "Disaster Recovery Planning. Technical plan for restoring IT systems. includes detailed procedures for recovering data and hardware to minimize operational downtime organizational-wide."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "RTO", "Back": "Recovery Time Objective. Maximum tolerable duration of system downtime. defines how quickly a business function must be restored after a disaster to avoid harm."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "RPO", "Back": "Recovery Point Objective. Maximum tolerable amount of data loss. determines the frequency of backups required to ensure information stays within acceptable organizational limits."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "DLP", "Back": "Data Loss Prevention. Technical solution preventing sensitive information from leaving. monitors and blocks restricted data in use, in motion, and at rest organizational-wide."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Honeypots", "Back": "Decoy systems designed to lure attackers. provide early organizational threat warning and help security teams study adversary methods without risking real information assets."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Sandboxing", "Back": "Isolated environment for analyzing suspicious files. prevents organizational malware from affecting systems while experts study behavior to develop effective detection and response strategies."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "SIEM", "Back": "Security Information and Event Management. Aggregates and analyzes log data to provide visibility and alerting for potential security incidents and cyber attacks."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Log Correlation", "Back": "Identifying patterns by linking events from different sources. used to detect sophisticated attacks that bypass individual organizational system security controls and mechanisms."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Egress Monitoring", "Back": "Evaluating traffic leaving the organizational network. used to detect unauthorized data exfiltration and prevent malware from communicating with external command and control servers."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "Incident Response Team", "Back": "Group of experts responsible for managing security breaches. includes technical, legal, and management personnel to ensure coordinated response to organizational cyber threats."},
        {"Topic": "7", "Subtopic": "N/A", "Front": "SOAR", "Back": "Security Orchestration, Automation, and Response. Integrated tools for security activities. automates repetitive tasks and orchestrates workflows, improving efficiency of organizational defensive efforts."},

        # Topic 8: Software Development Security
        {"Topic": "8", "Subtopic": "N/A", "Front": "DevSecOps", "Back": "Culture of shared organizational security responsibility. integrates automated protective tools into CI/CD pipelines to ensure continuous protection and compliance throughout software development."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "SBOM", "Back": "Software Bill of Materials. Comprehensive list of ingredients and dependencies. helps organizations manage third-party supply chain vulnerabilities and maintain software integrity."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Fuzzing", "Back": "Providing random or invalid data as program input. identifies organizational vulnerabilities like crashes and memory leaks that could be exploited by adversaries to compromise."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Secure Coding Standards", "Back": "Mandatory requirements for safe software development. ensure organizational developers use defensive techniques to prevent critical vulnerabilities like buffer overflows and injection during coding."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Input Sanitization", "Back": "Cleaning and validating all user inputs. prevents malicious data from reaching organizational systems and is essential for defending against various injection attacks."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Output Encoding", "Back": "Translating characters before browser rendering. prevents scripts from being executed as code, providing critical organizational defense against cross-site scripting and other application-layer attacks."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "SAST", "Back": "Static Application Security Testing. Examines organizational source code for vulnerabilities without execution, identifying common errors like injection flaws early in the lifecycle process."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "DAST", "Back": "Dynamic Application Security Testing. Tests running organizational software for flaws visible only during execution, such as session management errors and application-layer vulnerabilities."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "SCA", "Back": "Software Composition Analysis. Tool identifying vulnerabilities in third-party libraries. essential for securing organizational supply chains and ensuring all dependencies are updated and patched."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "IAST", "Back": "Interactive Application Security Testing. combines SAST and DAST to provide a comprehensive organizational view of software security by monitoring application behavior and code."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Feature Flags", "Back": "Mechanism for dynamically enabling software features. facilitates secure organizational testing and deployment by allowing risky components to be quickly turned off if vulnerabilities."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Canary Release", "Back": "Deploying updates to a small group first. identifies organizational issues early, minimizing the overall impact if software bugs or vulnerabilities are discovered in production."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "OWASP", "Back": "Open Web Application Security Project. provides a list of critical risks, serving as a primary focus for organizational secure coding and testing efforts."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Regression Testing", "Back": "Verifying that fixes remain effective after changes. ensures organizational updates do not reintroduce previously resolved vulnerabilities or compromise the overall application integrity and protection."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Secure Code Repository", "Back": "Storage system for source code with built-in security. ensures only authorized organizational developers can access and modify code, preventing unauthorized modifications and theft."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Environment Separation", "Back": "Maintaining distinct development, testing, and production environments. prevents unauthorized access and ensures untested code does not cause organizational operational disruptions or security gaps."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Immutable Infrastructure", "Back": "Infrastructure replaced rather than modified. reduces configuration drift and unauthorized changes, providing a secure and predictable environment for organizational software applications and systems."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Logic Flaw Detection", "Back": "Finding errors in software business rules. requires specialized organizational testing to identify vulnerabilities that allow bypass of access controls or perform unauthorized actions."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Software Hardening", "Back": "Securing applications by removing unnecessary features. reduces the organizational attack surface and strengthens the software's overall security posture against various cyber threats."},
        {"Topic": "8", "Subtopic": "N/A", "Front": "Zero Day Risk", "Back": "Previously unknown software vulnerability threats. requires organizational defense in depth and fast patching to protect against attackers exploiting new and unpatched gaps."}
    ]
}

def upload_data(data):
    try:
        response = requests.post(APPS_SCRIPT_URL, json=data, timeout=60)
        print(f"Status: {response.status_code}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    upload_data(data)
